export enum Cor{
    AMARELO = 'AMARELO',
    AZUL = 'AZUL',
    BEGE = 'BEGE',
    BRANCO = 'BRANCO',
    CINZA = 'CINZA',
    DOURADA = 'DOURADA',
    GRENÁ = 'GRENÁ',
    LARANJA = 'LARANJA',
    MARROM = 'MARROM',
    PRATA = 'PRATA',
    PRETO = 'PRETO',
    ROSA = 'ROSA',
    ROXA = 'ROXA',
    VERDE = 'VERDE',
    VERMELHA = 'VERMELHA',
    FANTASIA = 'FANTASIA',
}