export enum Marca{
    FIAT = 'FIAT',
    CHEVROLET = 'CHEVROLET',
    VOLKSWAGEN ='VOLKSWAGEN',
    TOYOTA = 'TOYOTA',
    HYUNDAI = 'HYUNDAI',
    RENAULT = 'RENAULT',
    HONDA = 'HONDA',
    VOLVO = 'VOLVO',
    SCANIA = 'SCANIA',
    MERCEDES = 'MERCEDES'
}
